.\" Process this file with
.\" groff -man -Tascii bareftp.1
.\"
.TH BAREFTP 1 "DECEMBER 2009"
.SH NAME
bareftp - graphical file transfer client
.SH SYNOPSIS
.B bareftp
.I "[OPTION] ..."

.SH DESCRIPTION
.B bareFTP
is a graphical file transfer client supporting the FTP, FTP over SSL/TLS
(FTPS) and SSH File Transfer Protocol (SFTP).
.BR bareFTP
is written in Python, using GTK+.
.BR bareFTP
is free and open source software released under the terms of 
the GPL license.
.SH OPTIONS
bareFTP does currently not use much command line options.
.TP
.B \-\-version
Show program version
.SH BUGS
If you find bugs, please report them at http://www.bareftp.org/devel
.SH AUTHOR
Christian Eide <christian@eide-itc.no> - http://www.bareftp.org
